// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEmCNgbRsyVVnAAlgyGMHu8gKTBx9Mw2w',
    appId: '1:453157086829:web:9a0f9230f56ad8c5d74164',
    messagingSenderId: '453157086829',
    projectId: 'login-screen-d7e31',
    authDomain: 'login-screen-d7e31.firebaseapp.com',
    databaseURL: 'https://login-screen-d7e31-default-rtdb.firebaseio.com',
    storageBucket: 'login-screen-d7e31.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlyYR9dRAWsr5tsWGv8u8Hhycd7XOoSUM',
    appId: '1:453157086829:android:d7d642f88008a6a6d74164',
    messagingSenderId: '453157086829',
    projectId: 'login-screen-d7e31',
    databaseURL: 'https://login-screen-d7e31-default-rtdb.firebaseio.com',
    storageBucket: 'login-screen-d7e31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0a4qIKlDLNxaOTIqdf2Si1mvTNRu5hWM',
    appId: '1:453157086829:ios:c937d1132ce54b5ad74164',
    messagingSenderId: '453157086829',
    projectId: 'login-screen-d7e31',
    databaseURL: 'https://login-screen-d7e31-default-rtdb.firebaseio.com',
    storageBucket: 'login-screen-d7e31.appspot.com',
    iosClientId: '453157086829-805aeoeanp0a5iqdo9gnpkluvhm4jouv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0a4qIKlDLNxaOTIqdf2Si1mvTNRu5hWM',
    appId: '1:453157086829:ios:c937d1132ce54b5ad74164',
    messagingSenderId: '453157086829',
    projectId: 'login-screen-d7e31',
    databaseURL: 'https://login-screen-d7e31-default-rtdb.firebaseio.com',
    storageBucket: 'login-screen-d7e31.appspot.com',
    iosClientId: '453157086829-805aeoeanp0a5iqdo9gnpkluvhm4jouv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
